// Auto-generated from xdropdown.html.
// DO NOT EDIT.

library x_dropdown;

import 'dart:html' as autogenerated;
import 'dart:svg' as autogenerated_svg;
import 'package:web_ui/web_ui.dart' as autogenerated;
import 'package:web_ui/observe/observable.dart' as __observe;
import 'package:web_ui/web_ui.dart';



class Dropdown extends WebComponent {
  /** Autogenerated from the template. */

  /** CSS class constants. */
  static Map<String, String> _css = {".dropdown-menu":"dropdown-menu",".btn":"btn",".dropdown-toggle":"dropdown-toggle",".dropdown-submenu":"dropdown-submenu",".dropup":"dropup",".open":"open",".dropdown":"dropdown"};

  /** This field is deprecated, use getShadowRoot instead. */
  get _root => getShadowRoot("x-dropdown");
  static final __shadowTemplate = new autogenerated.DocumentFragment.html('''
          <style>
button, html input[type="button"] {
  font-size: 14px;
  font-weight: normal;
  line-height: 20px;
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
  margin: 0;
  font-size: 100%;
  vertical-align: middle;
  *overflow: visible;
  line-height: normal;
  cursor: pointer;
  -webkit-appearance: button;
}
button::-moz-focus-inner, input::-moz-focus-inner {
  padding: 0;
  border: 0;
}
.dropup, .dropdown {
  position: relative;
}
.dropdown-toggle:active, .open .dropdown-toggle {
  outline: 0;
}
.dropdown-menu {
  position: absolute;
  top: 100%;
  left: 0;
  z-index: 1000;
  display: none;
  float: left;
  min-width: 160px;
  padding: 5px 0;
  margin: 2px 0 0;
  list-style: none;
  background-color: #fff;
  border: 1px solid #ccc;
  border: 1px solid rgba(0, 0, 0, 0.2);
  *border-right-width: 2px;
  *border-bottom-width: 2px;
  -webkit-border-radius: 6px;
  -moz-border-radius: 6px;
  border-radius: 6px;
  -webkit-box-shadow: 0 5px 10px rgba(0, 0, 0, 0.2);
  -moz-box-shadow: 0 5px 10px rgba(0, 0, 0, 0.2);
  box-shadow: 0 5px 10px rgba(0, 0, 0, 0.2);
  -webkit-background-clip: padding-box;
  -moz-background-clip: padding;
  background-clip: padding-box;
}
.btn {
  padding: 6px 30px;
  background-image: -moz-linear-gradient(top, #fff, #E6E6E6);
  background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#fff), to(#E6E6E6));
  background-image: -webkit-linear-gradient(top, #fff, #E6E6E6);
  background-image: -o-linear-gradient(top, #fff, #E6E6E6);
  background-image: linear-gradient(to bottom, #fff, #E6E6E6);
  background-repeat: repeat-x;
  border: 1px solid #CCC;
  border-color: #E6E6E6 #E6E6E6 #BFBFBF;
  border-color: rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.25);
  border-bottom-color: #B3B3B3;
}
.open {
  *z-index: 1000;
}
.open > .dropdown-menu {
  display: block;
}
.dropdown-menu > li > a {
  display: block;
  padding: 3px 20px;
  clear: both;
  font-weight: normal;
  line-height: 20px;
  color: #333;
  white-space: nowrap;
  cursor: pointer;
}
.dropdown-menu > li > a:hover, .dropdown-menu > li > a:focus, .dropdown-submenu:hover > a, .dropdown-submenu:focus > a {
  color: #fff;
  text-decoration: none;
  background-color: #0081C2;
  background-image: -moz-linear-gradient(top, #08C, #0077B3);
  background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#08C), to(#0077B3));
  background-image: -webkit-linear-gradient(top, #08C, #0077B3);
  background-image: -o-linear-gradient(top, #08C, #0077B3);
  background-image: linear-gradient(to bottom, #08C, #0077B3);
  background-repeat: repeat-x;
  cursor: pointer;
  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr=\'#ff0088cc\', endColorstr=\'#ff0077b3\', GradientType=0);
}
</style><button class="btn" data-toggle="dropdown">
            <content></content>
          </button>
          <content select="h2"></content>
      ''');
  autogenerated.Template __t;

  void created_autogenerated() {
    var __root = createShadowRoot("x-dropdown");
    __t = new autogenerated.Template(__root);
    __root.nodes.add(__shadowTemplate.clone(true));
    __t.create();
  }

  void inserted_autogenerated() {
    __t.insert();
  }

  void removed_autogenerated() {
    __t.remove();
    __t = null;
  }

  /** Original code from the component. */

  
}
//@ sourceMappingURL=xdropdown.dart.map